# Generated by Django 2.2.3 on 2019-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQTT', '0003_auto_20190730_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmqtt',
            name='password',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='authmqtt',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
